/**
 * Generates src/components/icons.tsx from the bootstrap-icons package.
 *
 * Run: node scripts/gen-icons.mjs
 *
 * Committed so the icon set is reproducible, but it is a one-shot tool — the
 * generated file is the artefact that ships. bootstrap-icons is removed from
 * dependencies afterwards (Task 13); re-running this requires reinstalling it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = resolve(root, 'node_modules/bootstrap-icons/icons');

// [ComponentName, bootstrap-icons filename]
const ICONS = [
  ['ChevronDown',         'chevron-down'],
  ['ChevronRight',        'chevron-right'],
  ['ChevronUp',           'chevron-up'],
  ['ChevronExpand',       'chevron-expand'],
  ['Search',              'search'],
  ['Regex',               'regex'],
  ['Download',            'download'],
  ['XLg',                 'x-lg'],
  ['CloudArrowUp',        'cloud-arrow-up'],
  ['ExclamationTriangle', 'exclamation-triangle'],
  ['BarChartLine',        'bar-chart-line'],
  ['Table',               'table'],
  ['ArrowLeft',           'arrow-left'],
];

/** Pull the inner markup out of a bootstrap-icons SVG file. */
function innerMarkup(name) {
  const svg = readFileSync(resolve(iconDir, `${name}.svg`), 'utf-8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  return body
    .replace(/fill-rule=/g, 'fillRule=')
    .replace(/clip-rule=/g, 'clipRule=')
    .replace(/stroke-width=/g, 'strokeWidth=')
    .replace(/stroke-linecap=/g, 'strokeLinecap=')
    .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
    .replace(/fill="#[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke="#[^"]*"/g, 'stroke="currentColor"')
    .trim();
}

const header = `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Source: bootstrap-icons (MIT). Re-generate with \`node scripts/gen-icons.mjs\`
// after reinstalling bootstrap-icons as a devDependency.

interface IconProps {
  className?: string;
  size?: number;
}

function svgProps(size: number, className?: string) {
  return {
    xmlns: 'http://www.w3.org/2000/svg',
    width: size,
    height: size,
    viewBox: '0 0 16 16',
    fill: 'currentColor',
    'aria-hidden': true,
    focusable: false,
    className,
  } as const;
}
`;

const body = ICONS.map(([component, file]) => `
export function ${component}({ className, size = 16 }: IconProps) {
  return (
    <svg {...svgProps(size, className)}>
      ${innerMarkup(file).replace(/\n/g, '\n      ')}
    </svg>
  );
}`).join('\n');

writeFileSync(resolve(root, 'src/components/icons.tsx'), header + body + '\n');
console.log(`Generated src/components/icons.tsx with ${ICONS.length} icons.`);
